name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    container:
      image: zzomrot/zksync-era-test-node-amd64:latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Start era-test-node
        run: |
          era_test_node --port 3050 fork mainnet &
          echo "SCRIPT_PID=$!" >> $GITHUB_ENV  # save process PID

      - run: yarn test:fork
        env:
          ZKSYNC_PRIVATE_KEY: ${{ secrets.ZKSYNC_PRIVATE_KEY }}

      - name: Stop era-test-node
        run: |
          ps -p ${{ env.SCRIPT_PID }}
          if ps -p ${{ env.SCRIPT_PID }} > /dev/null; then
            kill -9 ${{ env.SCRIPT_PID }}
          fi

  coverage:
    runs-on: ubuntu-latest
    container:
      image: zzomrot/zksync-era-test-node-amd64:latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Start era-test-node
        run: |
          era_test_node --port 3050 fork mainnet &
          echo "SCRIPT_PID=$!" >> $GITHUB_ENV  # save process PID

      - run: yarn coverage
        env:
          ZKSYNC_PRIVATE_KEY: ${{ secrets.ZKSYNC_PRIVATE_KEY }}

      - name: Stop era-test-node
        run: |
          ps -p ${{ env.SCRIPT_PID }}
          if ps -p ${{ env.SCRIPT_PID }} > /dev/null; then
            kill -9 ${{ env.SCRIPT_PID }}
          fi
      - uses: codecov/codecov-action@v3
